### ISSUE TITLE
Human-readable output?

### ISSUE THREAD

**Issue by PeterAJansen** [swarnaHub/PRover#2]
Hi there,

Is there a way to generate human-readable output for a given input -- for example, to generate output similar to Figure 2 in https://arxiv.org/pdf/2010.02830.pdf for the evaluation set?  (or, for an unseen example on the pretrained models?).  

I know scripts/get_results.sh outputs final accuracy numbers, and the prediction output generates a bunch of output files that are arrays of numbers representing nodes/edges -- but is there an existing tool (perhaps that you used during development) to inspect what these mean (in terms of Figure 2) in a human-readable way? 

thanks,
Peter

**Comment by swarnaHub** [comment]
Hi Peter,

Thanks for your interest! Check out this script and let me know if this serves your purpose 
https://github.com/swarnaHub/PRover/blob/master/evaluation/print_graphs.py

It works similarly to the evaluation script and will save the proofs as pdfs in the specified output directory.

**Comment by PeterAJansen** [comment]
Brilliant, thank you Swarnadeep!
